#!/usr/bin/env python3
"""Generate host adapters from shared roles/skills. --check performs no writes."""
import argparse
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]


def expected_files():
    roles = json.loads((ROOT / 'roles/registry.json').read_text(encoding='utf-8'))
    policy = json.loads((ROOT / 'config/policy.json').read_text(encoding='utf-8'))
    config = ['# Generated by scripts/sync_adapters.py. Models/permissions inherit the host.',
              '[agents]', 'enabled = true',
              f'max_concurrent_threads_per_session = {policy["max_parallel_workers"]}', '']
    files = {}
    for role in roles:
        name = role['name']
        prompt = '프로젝트 팀 역할입니다. 저장소 루트에서 실행합니다. AGENTS.md를 따릅니다.\n\n' + (ROOT / f'roles/{name}.md').read_text(encoding='utf-8')
        config += [f'[agents.{name}]', f'description = {json.dumps(role["description"], ensure_ascii=False)}',
                   f'config_file = "agents/{name}.toml"', '']
        files[f'.codex/agents/{name}.toml'] = 'developer_instructions = ' + json.dumps(prompt, ensure_ascii=False) + '\n'
        files[f'.claude/agents/{name}.md'] = f'---\nname: {name}\ndescription: {role["description"]}\nmodel: inherit\n---\n\n{prompt}'
    files['.codex/config.toml'] = '\n'.join(config)
    for source in sorted((ROOT / '.agents/skills').rglob('*')):
        if source.is_file():
            rel = source.relative_to(ROOT / '.agents/skills')
            files[str(Path('.claude/skills') / rel)] = source.read_text(encoding='utf-8')
    for name, body in files.items():
        if name.endswith('.toml'):
            tomllib.loads(body)
    return files


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    files = expected_files()
    differences = []
    # Only known generated directories are inspected, never user/global settings.
    generated = {str(p.relative_to(ROOT)) for folder in ('.codex/agents', '.claude/agents', '.claude/skills')
                 for p in (ROOT / folder).rglob('*') if p.is_file()}
    stale = sorted(generated - set(files))
    for name, body in files.items():
        path = ROOT / name
        if not path.exists() or path.read_text(encoding='utf-8') != body:
            differences.append(name)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(body, encoding='utf-8')
    if stale:
        print('더 이상 원본에 없는 배포본을 검토하세요. 자동 삭제하지 않습니다:', *stale, sep='\n')
    if args.check and differences:
        print('배포본 갱신 필요:', *differences, sep='\n')
    if stale or (args.check and differences):
        return 1
    print(f'호스트 설정 {len(files)}개: ' + ('일치 확인' if args.check else '동기화 완료'))
    return 0


if __name__ == '__main__':
    sys.exit(main())
